/**
 * @file agent-test.js
 * @description Real k6 performance test — TC-001/US-42, output of the WP-12 agent pipeline.
 *
 * Generated by: ANALYZE (demo/openapi/sample-api.json) -> PLAN (US-42) -> GENERATE
 * User story:   US-42 "As a dog enthusiast I want to browse breeds"
 * Test case:    TC-001 -- GET /api/v2/breeds
 * Approval:     API shall respond with status code 200
 *
 * Steps:
 * - "Create a new HttpClient"
 * - "GET /api/v2/breeds"
 * - "Verify that breeds list returns a 200 status code"
 * @example
 * How to run:
 * ```shell
 * k6 run agent-test.js
 * # Or by using build the docker image and run the test
 * docker build -t agents-pipeline-test .
 * docker run -i --rm --net=host -e API_SERVER=dogapi.dog agents-pipeline-test:latest
 * ```
 * @author Aydin Abdi <ayd.abd@gmail.com>
 * @license MIT
 */

import { group, sleep } from 'k6';
import { HttpClientFactory } from '../src/clients/http-client.js';

// Define environment variables
const K6_API_SERVER = __ENV.API_SERVER || 'dogapi.dog'; // eslint-disable-line no-undef
const DEFAULT_API_HEADERS = {
    "Content-Type": "application/json",
    "User-Agent": "k6-agent-pipeline-test",
    "Cache-Control": "no-cache, no-store, must-revalidate",
    "Pragma": "no-cache"
};


/**
 * Setup.
 * @see https://grafana.com/docs/k6/latest/using-k6/test-lifecycle
 * @see https://k6.io/docs/using-k6/test-life-cycle
 */
export function setup() {
    try {
        console.debug('Setup'); // eslint-disable-line no-undef
    } catch (error) {
        console.error('Error in setup:', error); // eslint-disable-line no-undef
        teardown();
    }
}


/**
 * Teardown function to close the API client
 * @see https://grafana.com/docs/k6/latest/using-k6/test-lifecycle/
 */
export function teardown() {
    console.debug('Teardown'); // eslint-disable-line no-undef
}


/**
 * TC-001 -- GET /api/v2/breeds (US-42)
 * Description: "Agent-pipeline-generated test: verify breeds endpoint returns 200"
 * Approvals:
 * - "Api shall respond with status code 200"
 * - "Thresholds for duration and failed requests shall be met"
 * Steps:
 * - "Create a new HttpClient"
 * - "Verify that breeds list returns a 200 status code"
 */
export default function () {
    const httpOpt = {
        host: K6_API_SERVER,
        headers: DEFAULT_API_HEADERS,
    };
    let { dynamicClient } = new HttpClientFactory(httpOpt);

    group('[TC-001] Verify that breeds list returns a 200 status code', () => {
        dynamicClient.api.v2.breeds.get(); // https://dogapi.dog/api/v2/breeds
    });
    sleep(1);
}
