/**
 * @file agent-test.js
 * @description Real k6 performance test generated by the WP-12 agent pipeline.
 *
 * Pipeline run against: demo/openapi/sample-api.json (Dog CEO API)
 * User story:           US-42 - As a dog enthusiast I want to browse breeds
 *
 * This script is the exact output of running the agent pipeline end-to-end:
 *   ANALYZE (sample-api.json) → PLAN (US-42) → GENERATE
 *
 * It proves that the generated scripts are valid k6 ES modules that actually
 * work in production — against the real Dog CEO public API.
 *
 * Run manually:
 * ```shell
 * k6 run agent-test.js
 * # Or via Docker (build base image first):
 * docker build -t k6-template-influxdb-base:latest .
 * docker build -t agents-pipeline-test:latest -f agents-pipeline-test/Dockerfile .
 * docker run --rm -e API_SERVER=dogapi.dog agents-pipeline-test:latest
 * ```
 * @author Aydin Abdi <ayd.abd@gmail.com>
 * @license MIT
 */

import { TestCaseBuilder } from '../src/test-case.js';
import { HttpClientFactory } from '../src/clients/http-client.js';

/** @type {string} Target API server, injected via Docker/k8s ENV */
const API_SERVER = __ENV.API_SERVER || 'dogapi.dog'; // eslint-disable-line no-undef

/**
 * k6 options — thresholds derived from US-42 acceptance criteria:
 *   - p95 response time under 500 ms
 *   - error rate below 1%
 */
export const options = {
    thresholds: {
        http_req_duration: ['p(95)<500'],
        http_req_failed: ['rate<0.01'],
    },
};

/**
 * TC-001 — GET /api/v2/breeds (US-42)
 * Verifies that the breeds list endpoint responds with HTTP 200.
 */
export default function () {
    const tc001 = new TestCaseBuilder('TC-001', 'GET /api/v2/breeds')
        .steps(['GET /api/v2/breeds', 'Assert 200', 'Assert response body'])
        .tags({ testType: 'acceptance-requirements', userStory: 'US-42' })
        .build();

    tc001.toK6Group(() => {
        const { dynamicClient } = new HttpClientFactory({ host: API_SERVER });
        dynamicClient.api.v2.breeds.get();
    });
}
