/**
 * @file agent-test.js
 * @description Real k6 performance test — output of the WP-12 agent pipeline.
 *
 * Generated by: ANALYZE (demo/openapi/sample-api.json) → PLAN (US-42) → GENERATE
 * User story:   US-42 "As a dog enthusiast I want to browse breeds"
 *
 * Test case:    TC-001 — GET /api/v2/breeds
 * Approval:     API shall respond with status code 200
 * Steps:
 *   1. Create an HttpClient targeting the API server
 *   2. GET /api/v2/breeds
 *   3. Verify 200 status code
 *
 * This script proves the agent-generated output is a valid, runnable k6 ES module
 * that can be containerised and deployed to Docker and Kubernetes exactly like every
 * other test in this repository.
 *
 * Run manually:
 * ```shell
 * k6 run agent-test.js
 * # Or via Docker (build base image first):
 * docker build -t k6-template-influxdb-base:latest .
 * docker build -t agents-pipeline-test:latest -f agents-pipeline-test/Dockerfile .
 * docker run --rm -e API_SERVER=dogapi.dog agents-pipeline-test:latest
 * ```
 * @author Aydin Abdi <ayd.abd@gmail.com>
 * @license MIT
 */

import { group, sleep } from 'k6';
import { HttpClientFactory } from '../src/clients/http-client.js';

/** @type {string} Target API server, injected via Docker/k8s ENV */
const API_SERVER = __ENV.API_SERVER || 'dogapi.dog'; // eslint-disable-line no-undef

const DEFAULT_API_HEADERS = {
    "Content-Type": "application/json",
    "User-Agent": "k6-agent-pipeline-test",
    "Cache-Control": "no-cache, no-store, must-revalidate",
    "Pragma": "no-cache",
};

/**
 * Setup.
 * @see https://grafana.com/docs/k6/latest/using-k6/test-lifecycle
 */
export function setup() {
    console.debug('Setup'); // eslint-disable-line no-undef
}

/**
 * Teardown.
 * @see https://grafana.com/docs/k6/latest/using-k6/test-lifecycle
 */
export function teardown() {
    console.debug('Teardown'); // eslint-disable-line no-undef
}

/**
 * TC-001 — GET /api/v2/breeds (US-42)
 * Agent-generated default function: verifies the Dog API breeds endpoint.
 */
export default function () {
    const httpOpt = {
        host: API_SERVER,
        headers: DEFAULT_API_HEADERS,
    };
    const { dynamicClient } = new HttpClientFactory(httpOpt);

    group('[TC-001] GET /api/v2/breeds — agent-generated', () => {
        dynamicClient.api.v2.breeds.get(); // https://dogapi.dog/api/v2/breeds
    });

    sleep(1);
}
