services:
  influxdb:
    image: influxdb:latest
    networks:
      - k6-webnet
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=k6test
      # influxdb password shall be at least 8 characters
      - DOCKER_INFLUXDB_INIT_PASSWORD=k6testme
      - DOCKER_INFLUXDB_INIT_ORG=k6testorg
      - DOCKER_INFLUXDB_INIT_BUCKET=simple-k6-tests
      # Use docker secret instead of hardcoded for security reasons
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=y3zTEWhDLPfa05-op-gKftVHhbEkmNL98uijqokTMr_JHdlK59PpitKl6QdXNF3YQVrLXdtTdjISNSqWtFwbFw==
    volumes:
      - k6-influxdb-data:/var/lib/influxdb2
      - k6-influxdb-config:/etc/influxdb2

  grafana:
    image: grafana/grafana-enterprise:latest
    depends_on:
      - influxdb
    networks:
      - k6-webnet
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - k6-grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - influxdb
      - grafana
    networks:
      - k6-webnet

  k6-template-influxdb-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: k6-template-influxdb-base:latest
    volumes:
      - /usr/share/zoneinfo/UTC:/etc/localtime:ro
    networks:
      - k6-webnet

  simple-k6-test-template:
    depends_on:
      - k6-template-influxdb-base
      - influxdb
      - nginx
    build:
      context: .
      dockerfile: simple-k6-test-template/Dockerfile
    image: simple-k6-test-template:latest
    volumes:
      - ./simple-k6-test-template/test-logs:/performance-k6/test-logs
    networks:
      - k6-webnet

  websocket-echo:
    image: jmalloc/echo-server
    ports:
      - "9001:8080"
    networks:
      - k6-webnet
    restart: unless-stopped

  simple-k6-websocket-test:
    image: simple-k6-websocket-test:latest
    build:
      context: .
      dockerfile: simple-k6-websocket-test/Dockerfile
    depends_on:
      - k6-template-influxdb-base
      - influxdb
      - nginx
      - websocket-echo
    environment:
      - API_SERVER=websocket-echo
    volumes:
      - ./simple-k6-websocket-test/test-logs:/performance-k6/test-logs
    networks:
      - k6-webnet

volumes:
  k6-influxdb-data: {}
  k6-influxdb-config: {}
  k6-grafana-data: {}

networks:
  k6-webnet:
