#!/bin/sh
##############################################################
# ====================
# Linters and jsdoc2md
# ====================
# @ Author: Aydin Abdi <ayd.abd@gmail.com>
# @ License: MIT
#
# This script runs linters (eslint, markdownlint) and jsdoc2md
# based on package.json 'scripts' section.
# It also installs npm packages from package.json.
# It is intended to be run as part of the git pre-commit hook.
##############################################################

usage_help() {
    cat <<EOF
Usage: $(basename $0) [options]

Description:
  This script runs linters (eslint, markdownlint) and jsdoc2md based on package.json 'scripts' section.
  It also installs npm packages from package.json.

Options:
  -i, --install-npm-packages  Install npm packages from package.json
  --eslint                    Run eslint based on package.json 'scripts' section
  --markdownlint              Run markdownlint based on package.json 'scripts' section
  -a, --all-linters           Run all linters (eslint, markdownlint)
  -d, --jsdoc2md              Run jsdoc2md to generate markdown documentation
  -h, --help                  Display this help and exit

Examples:
    $(basename $0) --install-npm-packages
    $(basename $0) -a

EOF
}

# install npm packages from package.json
install_npm_packages() {
  # check if package.json exists
  if [ -f package.json ]; then
    # install npm packages
    npm install --no-save --no-fund --no-audit || return 1
    npm update --no-fund --no-audit || return 1
  else
    printf "package.json not found"
    return 1
  fi
}


# run eslint and its plugins based on package.json 'scripts' section
run_eslint() {
  if [ -f package.json ]; then
    npm run eslint || return 1
  else
    printf "package.json not found"
    return 1
  fi
}

# run markdown linter based on package.json 'scripts' section
run_markdownlint() {
  if [ -f package.json ]; then
    npm run markdownlint || return 1
  else
    printf "package.json not found"
    return 1
  fi
}

# run all linters (eslint, markdownlint)
run_all_linters() {
  install_npm_packages || return 1
  run_eslint || return 1
  run_markdownlint || return 1
}

# run jsdoc2md to generate markdown documentations based on package.json 'scripts' section
# it generates markdown files in 'docs' directory for several folders
run_jsdoc2md() {
  if [ -f package.json ]; then
    install_npm_packages || return 1
    npm run jsdoc2mdClient || return 1
  else
    printf "package.json not found"
    return 1
  fi
}

# main function
main() {
  exit_code=0
  case $1 in
    -h|--help)
      usage_help || exit_code=0
      ;;
    -i|--install-npm-packages)
      install_npm_packages || exit_code=1
      ;;
    --eslint)
      run_eslint || exit_code=1
      ;;
    --markdownlint)
      run_markdownlint || exit_code=1
      ;;
    -a|--all-linters)
      run_all_linters || exit_code=1
      ;;
    -d|--jsdoc2md)
      run_jsdoc2md || exit_code=1
      ;;
    *)
      usage_help || exit_code=1
      ;;
  esac

  if [ $exit_code -eq 1 ]; then
    exit 1
  fi
}

main $1
