apiVersion: v1
kind: Secret
metadata:
  name: k6-influxdb-credentials
  namespace: k6-tests
type: Opaque
stringData:
  username: ${INFLUXDB_USERNAME}
  password: ${INFLUXDB_PASSWORD}
  org: ${INFLUXDB_ORG}
  bucket: ${INFLUXDB_BUCKET}
  token: ${INFLUXDB_TOKEN}
