apiVersion: batch/v1
kind: Job
metadata:
  name: k6-business-flow
  namespace: k6-tests
  labels:
    app: k6-business-flow
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6-business-flow
          image: business-flow-template:2.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: BUSINESS_FLOW_NAME
              value: "default-flow"
            - name: TEST_RUN_ID
              value: "${TEST_RUN_ID}"
            - name: K6_OTEL_EXPORTER_PROTOCOL
              value: "grpc"
            - name: K6_TAGS
              value: "testRunId:${TEST_RUN_ID}"
            - name: K6_OTEL_GRPC_EXPORTER_ENDPOINT
              value: "otel-collector:4317"
            - name: K6_OTEL_GRPC_EXPORTER_INSECURE
              value: "true"
