apiVersion: v1
kind: Service
metadata:
  name: websocket-echo
  namespace: k6-tests
spec:
  selector:
    app: websocket-echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-echo
  namespace: k6-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-echo
  template:
    metadata:
      labels:
        app: websocket-echo
    spec:
      containers:
        - name: websocket-echo
          image: jmalloc/echo-server:latest
          ports:
            - containerPort: 8080
