{
 "title": "K6 Performance Tests",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "http_reqs",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\n  |> yield(name: \"Maximum Number of Virtual Users\")"
    }
   ]
  },
  {
   "title": "iterations",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iterations\")\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\n  |> yield(name: \"Sum of iterations\")"
    }
   ]
  },
  {
   "title": "http_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> group(columns: [\"name\", \"status\"])\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\n  |> yield(name: \"Max http_req_duration\")"
    }
   ]
  },
  {
   "title": "Top 20 slowest http requests",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\r\n    |> group(columns: [\"_measurement\"])\r\n    |> top(columns: [\"_value\"], n: 100)\r\n    |> keep(columns: [\"name\", \"status\", \"_measurement\", \"_value\"])\r\n    |> yield(name: \"Top Slowest Request Duration\")"
    }
   ]
  },
  {
   "title": "ws_session_duration",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ws_session_duration\")\r\n  |> yield(name: \"Web socket session duration\")"
    }
   ]
  }
 ]
}