apiVersion: 1

datasources:
  - name: K6InfluxDB
    type: influxdb
    url: http://influxdb:8086
    isDefault: true
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
    jsonData:
      version: Flux
      organization: $__env{INFLUXDB_ORG}
      defaultBucket: $__env{INFLUXDB_BUCKET}
      maxSeries: 10000
  - name: Tempo
    type: tempo
    url: http://grafana-tempo:3200
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
