name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run pre-commit hooks
        run: pip install pre-commit && pre-commit run --all-files -c .githooks.d/.pre-commit-config.yaml

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests for http client
        run: ./ci-deployment -d simple-k6-test-template
      - name: Run integration tests for ws client
        run: ./ci-deployment -d simple-k6-websocket-test -s websocket-echo

  integration-tests-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: k6
      - name: Run integration tests on Kubernetes
        env:
          KUBECTL_CONTEXT: k3d-k6
        run: ./k8s-deployment -a
