
name: Docker Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/k6-template-influxdb-base:${{ github.ref_name }} .
          docker push ghcr.io/${{ github.repository }}/k6-template-influxdb-base:${{ github.ref_name }}

          docker build \
            --build-arg BASE_IMAGE_NAME=ghcr.io/${{ github.repository }}/k6-template-influxdb-base \
            --build-arg BASE_IMAGE_VERSION=${{ github.ref_name }} \
            -t ghcr.io/${{ github.repository }}/simple-k6-test-template:${{ github.ref_name }} \
            -f simple-k6-test-template/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/simple-k6-test-template:${{ github.ref_name }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Docker Images

            - [`ghcr.io/${{ github.repository }}/k6-template-influxdb-base:${{ github.ref_name }}`](https://ghcr.io/${{ github.repository }}/k6-template-influxdb-base)
            - [`ghcr.io/${{ github.repository }}/simple-k6-test-template:${{ github.ref_name }}`](https://ghcr.io/${{ github.repository }}/simple-k6-test-template)
